version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: DockerfileDatabase
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - db_data:/usr/src/data-backup
    networks:
      app_network:
        ipv4_address: 192.168.56.11

  web:
    build:
      context: .
      dockerfile: DockerfileWeb
    ports:
      - "8080:8080"
    networks:
      app_network:
        ipv4_address: 192.168.56.10
    depends_on:
      - db

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
